name: Deploy Dependencies (with approval)
run-name: Deploy Dependencies on ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - ""
jobs:
  approve:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.GH_APPROVERS }} # comma separated list of GitHub usernames
          minimum-approvals: 1
          issue-title: 'Deploy (${{ github.event.inputs.environment }}): core: ${{ github.event.inputs.core-image-tag }} country config: ${{ github.event.inputs.countryconfig-image-tag }}'
          issue-body: 'Please approve or deny the deployment of core: ${{ github.event.inputs.core-image-tag }} country config: ${{ github.event.inputs.countryconfig-image-tag }} to ${{ github.event.inputs.environment }}'
          exclude-workflow-initiator-as-approver: false
  github-to-k8s-sync-env:
    uses: ./.github/workflows/github-to-k8s-sync-env.yml
    with:
      environment: ${{ inputs.environment }}
      mapping_file: "deps"
    secrets: inherit
  deploy:
    needs: github-to-k8s-sync-env
    environment: ${{ inputs.environment }}
    env:
      ENV: ${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: Install traefik
        run: |
          kubectl scale deployment traefik --replicas=0 --namespace traefik || true
          helm upgrade --install traefik oci://ghcr.io/traefik/helm/traefik \
            --namespace traefik \
            --create-namespace \
            -f environments/${ENV}/traefik/values.yaml
          kubectl scale deployment traefik --replicas=1 --namespace traefik
      - name: Install OpenCRVS dependencies
        run: |
          helm upgrade --install opencrvs-deps oci://ghcr.io/opencrvs/opencrvs-dependencies-chart \
            --namespace "opencrvs-deps-${ENV}" \
            -f environments/${ENV}/dependencies/values.yaml \
            --create-namespace \
            --set hostname=${{ vars.DOMAIN }} \
            --atomic
