name: Sync GitHub env to Kubernetes
run-name: Sync GitHub env to Kubernetes for ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - demo1
          - production
          - staging
      mapping_file:
        description: "Secrets mapping template"
        default: "opencrvs"
        type: choice
        options:
          - opencrvs
          - deps     
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      mapping_file:
        type: string
        default: opencrvs 

jobs:
  sync-env:
    environment: ${{ inputs.environment }}
    env:
      mapping_file: ${{ inputs.mapping_file || 'opencrvs' }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v5
      - name: Export all secrets and environment variables
        run: |
            # Create a temporary file for environment variables
            ENV_FILE=$(mktemp)
            jq -n -r '
                [${{ toJSON(secrets) }}, ${{ toJSON(vars) }}] 
                | add
                | to_entries
                | map(select(.value | test("\n") | not))
                | map("\(.key)=\"\(.value)\"")
                | .[]
            ' > $ENV_FILE

            echo env_file=$ENV_FILE >> $GITHUB_ENV
            cat $ENV_FILE
      - name: Preprocess mapping into Secret YAMLs
        run: |
          set -euo pipefail
          mkdir -p k8s-secrets

          mapping_file=".github/TEMPLATES/secret-mapping-${mapping_file}.yml"

          # Iterate over all kubernetes secret names in mapping
          for secret_name in $(yq e 'keys | .[]' "$mapping_file"); do
          skip_manifest=false
          echo "🔧 Generating Secret: $secret_name"

          {
            echo "apiVersion: v1"
            echo "kind: Secret"
            echo "metadata:"
            echo "  name: $secret_name"
            echo "type: Opaque"
            echo "stringData:"
            while IFS= read -r key; do
              # Skip comments
              if echo "$key" | grep -q "^[[:space:]]*#"; then
                continue
              fi

              if echo "$key" | grep -q ":"; then
                github_var=$(echo "$key" | cut -d: -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                k8s_var=$(echo "$key" | cut -d: -f2 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              else
                github_var="$key"
                k8s_var="$key"
              fi

              value=$(grep "^$github_var=" "$env_file" | cut -d= -f2- || true)

              if [ -n "$value" ]; then
                echo "  $k8s_var: $value"
              else
                echo "⚠️  Warning: $github_var not found in env_file → setting $k8s_var as empty" >&2
                echo "  $k8s_var: ''"
                skip_manifest=true
              fi
            done < <(yq e ".\"$secret_name\"[]" "$mapping_file")
          } > "k8s-secrets/$secret_name.yaml"
          if [ "$skip_manifest" == "true" ]; then
            echo "⚠️  Skipping Kubernetes secret $secret_name due to empty or not defined GitHub secrets or variables"
            rm -f "k8s-secrets/$secret_name.yaml"
          fi
          done

          echo "✅ Generated manifests:"
          ls -l k8s-secrets

      - name: Apply secrets to Kubernetes
        run: |
          set -euo pipefail
          if [ "$mapping_file" = "opencrvs" ]; then
            namespace="opencrvs-${{ inputs.environment || 'demo' }}"
          else
            namespace="opencrvs-deps-${{ inputs.environment || 'demo' }}"
          fi
          echo "ℹ️  Using namespace: $namespace"
          kubectl get namespace $namespace >/dev/null 2>&1 || kubectl create namespace $namespace
          for f in k8s-secrets/*.yaml; do
            echo "🚀 Applying $f"
            yq eval . "$f" > /dev/null && echo "✅ $f is valid YAML" || echo "❌ $f has YAML errors" && cat "$f"
            kubectl apply -n $namespace -f "$f"
          done

      - name: Cleanup secrets and variables
        if: always()
        run: |
          rm -fv $env_file
          rm -fvr k8s-secrets
